export interface Product {
  id: string
  name: string
  price: number
  originalPrice?: number
  image: string
  rating: number
  reviews: number
  category: string
  subcategory: string
  brand: string
  description: string
  specifications: Record<string, string>
  inStock: boolean
  colors?: string[]
  href: string
}

export const hardwareProducts: Product[] = [
  {
    id: "1",
    name: "Teclado Mecânico RGB Gamer",
    price: 299.0,
    originalPrice: 399.0,
    image: "/images/teclado-mecanico-rgb.png",
    rating: 4.8,
    reviews: 234,
    category: "Hardware",
    subcategory: "Teclados",
    brand: "TechGamer",
    description:
      "Teclado mecânico gamer com switches azuis, iluminação RGB personalizável, teclas anti-ghosting e design ergonômico para máxima performance em jogos.",
    specifications: {
      Tipo: "Mecânico",
      Layout: "ABNT2",
      Switches: "Azuis",
      Teclas: "104",
      Conexão: "USB 2.0",
      Cabo: "1.8m trançado",
      "Polling Rate": "1000Hz",
      "Anti-ghosting": "Sim",
    },
    inStock: true,
    colors: ["Preto", "Branco", "RGB"],
    href: "/produto/teclado-mecanico-rgb-gamer",
  },
  {
    id: "2",
    name: "Mouse Gamer RGB 12000 DPI",
    price: 159.0,
    originalPrice: 199.0,
    image: "/images/mouse-gamer-rgb.png",
    rating: 4.6,
    reviews: 189,
    category: "Hardware",
    subcategory: "Mouses",
    brand: "TechGamer",
    description: "Mouse gamer de alta precisão com sensor óptico de 12000 DPI, iluminação RGB e 8 botões programáveis.",
    specifications: {
      DPI: "12000",
      Sensor: "Óptico",
      Botões: "8 programáveis",
      Conexão: "USB",
      Cabo: "1.8m",
      Peso: "95g",
    },
    inStock: true,
    colors: ["Preto", "Branco"],
    href: "/produto/mouse-gamer-12000-dpi",
  },
  {
    id: "3",
    name: 'Monitor Gaming 27" G-SYNC 144Hz',
    price: 1299.0,
    originalPrice: 1599.0,
    image: "/images/monitor-gaming-27.png",
    rating: 4.9,
    reviews: 156,
    category: "Hardware",
    subcategory: "Monitores",
    brand: "ViewTech",
    description: "Monitor gamer de 27 polegadas com tecnologia G-SYNC, taxa de atualização de 144Hz e resolução QHD.",
    specifications: {
      Tamanho: "27 polegadas",
      Resolução: "2560x1440 (QHD)",
      "Taxa de Atualização": "144Hz",
      Tecnologia: "G-SYNC",
      Painel: "IPS",
      "Tempo de Resposta": "1ms",
    },
    inStock: true,
    href: "/produto/monitor-27-144hz-gaming",
  },
  {
    id: "4",
    name: "Headset Gamer RGB 7.1 Surround",
    price: 249.0,
    originalPrice: 299.0,
    image: "/images/headset-gamer-rgb.png",
    rating: 4.7,
    reviews: 298,
    category: "Hardware",
    subcategory: "Headsets",
    brand: "SoundMax",
    description: "Headset gamer com som surround 7.1, microfone removível e iluminação RGB.",
    specifications: {
      Som: "7.1 Surround",
      Drivers: "50mm",
      Microfone: "Removível",
      Conexão: "USB + P2",
      Cabo: "2m",
    },
    inStock: true,
    colors: ["Preto", "Vermelho"],
    href: "/produto/headset-gamer-71-surround",
  },
  {
    id: "5",
    name: "Webcam Logitech 4K Ultra HD",
    price: 399.0,
    originalPrice: 499.0,
    image: "/images/webcam-logitech.png",
    rating: 4.5,
    reviews: 87,
    category: "Hardware",
    subcategory: "Webcams",
    brand: "Logitech",
    description: "Webcam profissional com resolução 4K, autofoco e microfone integrado.",
    specifications: {
      Resolução: "4K (3840x2160)",
      FPS: "30fps",
      Autofoco: "Sim",
      Microfone: "Integrado",
      Conexão: "USB 3.0",
    },
    inStock: true,
    href: "/produto/webcam-4k-ultra-hd",
  },
  {
    id: "6",
    name: "SSD Kingston 1TB NVMe M.2",
    price: 449.0,
    originalPrice: 549.0,
    image: "/images/ssd-nvme-kingston.png",
    rating: 4.8,
    reviews: 412,
    category: "Hardware",
    subcategory: "Armazenamento",
    brand: "Kingston",
    description: "SSD NVMe M.2 de 1TB com velocidades de leitura de até 3500 MB/s.",
    specifications: {
      Capacidade: "1TB",
      Interface: "NVMe M.2",
      Leitura: "3500 MB/s",
      Escrita: "2900 MB/s",
      Formato: "M.2 2280",
    },
    inStock: true,
    href: "/produto/ssd-1tb-nvme-m2",
  },
]

export const smartphonesProducts: Product[] = [
  {
    id: "15",
    name: "iPhone 14 Pro 128GB Roxo",
    price: 6999.0,
    originalPrice: 7999.0,
    image: "/images/iphone-14-pro-purple.png",
    rating: 4.9,
    reviews: 1234,
    category: "Smartphones & Tablets",
    subcategory: "iPhone",
    brand: "Apple",
    description:
      "iPhone 14 Pro com chip A16 Bionic, sistema de câmera Pro de 48MP e tela Super Retina XDR de 6,1 polegadas.",
    specifications: {
      Tela: "6,1 polegadas Super Retina XDR",
      Chip: "A16 Bionic",
      Armazenamento: "128GB",
      "Câmera Principal": "48MP",
      "Câmera Frontal": "12MP",
      Bateria: "Até 23h de vídeo",
      Resistência: "IP68",
    },
    inStock: true,
    colors: ["Roxo Profundo", "Dourado", "Prateado", "Preto Espacial"],
    href: "/produto/iphone-14-pro-128gb",
  },
  {
    id: "16",
    name: "Samsung Galaxy S22 Ultra 256GB",
    price: 5499.0,
    originalPrice: 6299.0,
    image: "/images/samsung-galaxy-s22-ultra.png",
    rating: 4.8,
    reviews: 987,
    category: "Smartphones & Tablets",
    subcategory: "Samsung",
    brand: "Samsung",
    description: "Galaxy S22 Ultra com S Pen integrada, câmera de 108MP e tela Dynamic AMOLED 2X de 6,8 polegadas.",
    specifications: {
      Tela: "6,8 polegadas Dynamic AMOLED 2X",
      Processador: "Snapdragon 8 Gen 1",
      Armazenamento: "256GB",
      "Câmera Principal": "108MP",
      "Câmera Frontal": "40MP",
      Bateria: "5000mAh",
      "S Pen": "Incluída",
    },
    inStock: true,
    colors: ["Phantom Black", "Phantom White", "Burgundy", "Green"],
    href: "/produto/samsung-galaxy-s22-ultra",
  },
  {
    id: "17",
    name: 'iPad Pro 12.9" M2 128GB Wi-Fi',
    price: 8999.0,
    image: "/images/ipad-pro-12.png",
    rating: 4.9,
    reviews: 567,
    category: "Smartphones & Tablets",
    subcategory: "iPad",
    brand: "Apple",
    description:
      "iPad Pro com chip M2, tela Liquid Retina XDR de 12,9 polegadas e suporte ao Apple Pencil de 2ª geração.",
    specifications: {
      Tela: "12,9 polegadas Liquid Retina XDR",
      Chip: "Apple M2",
      Armazenamento: "128GB",
      Conectividade: "Wi-Fi 6E",
      "Câmera Principal": "12MP",
      "Câmera Frontal": "12MP Ultra Wide",
      Bateria: "Até 10h de uso",
    },
    inStock: true,
    colors: ["Cinza Espacial", "Prateado"],
    href: "/produto/ipad-pro-12-m2",
  },
  {
    id: "18",
    name: "Redmi Note 12 Pro 128GB Azul",
    price: 1299.0,
    originalPrice: 1599.0,
    image: "/images/redmi-note-12.png",
    rating: 4.6,
    reviews: 432,
    category: "Smartphones & Tablets",
    subcategory: "Xiaomi",
    brand: "Xiaomi",
    description: "Redmi Note 12 Pro com câmera de 50MP, tela AMOLED de 6,67 polegadas e carregamento rápido de 67W.",
    specifications: {
      Tela: "6,67 polegadas AMOLED",
      Processador: "MediaTek Dimensity 1080",
      Armazenamento: "128GB",
      "Câmera Principal": "50MP",
      "Câmera Frontal": "16MP",
      Bateria: "5000mAh",
      Carregamento: "67W",
    },
    inStock: true,
    colors: ["Azul Glacial", "Preto Grafite", "Branco Polar"],
    href: "/produto/redmi-note-12-pro",
  },
  {
    id: "19",
    name: "Samsung Galaxy Tab S8+ com Teclado",
    price: 3999.0,
    originalPrice: 4599.0,
    image: "/images/samsung-tablet-keyboard.png",
    rating: 4.7,
    reviews: 234,
    category: "Smartphones & Tablets",
    subcategory: "Tablets",
    brand: "Samsung",
    description:
      "Galaxy Tab S8+ com tela de 12,4 polegadas, S Pen incluída e teclado destacável para máxima produtividade.",
    specifications: {
      Tela: "12,4 polegadas Super AMOLED",
      Processador: "Snapdragon 8 Gen 1",
      Armazenamento: "128GB",
      "Câmera Principal": "13MP",
      "Câmera Frontal": "12MP",
      Bateria: "10090mAh",
      Acessórios: "S Pen + Teclado",
    },
    inStock: true,
    colors: ["Grafite", "Prata", "Rosa Dourado"],
    href: "/produto/galaxy-tab-s8-plus",
  },
  {
    id: "20",
    name: "Cabo Lightning para USB-C 1m",
    price: 89.0,
    originalPrice: 129.0,
    image: "/images/cabo-lightning.png",
    rating: 4.4,
    reviews: 156,
    category: "Smartphones & Tablets",
    subcategory: "Acessórios",
    brand: "Apple",
    description: "Cabo Lightning para USB-C original Apple, ideal para carregamento e sincronização de dados.",
    specifications: {
      Comprimento: "1 metro",
      Conectores: "Lightning para USB-C",
      Compatibilidade: "iPhone, iPad, iPod",
      Material: "Cabo trançado",
      Certificação: "MFi",
    },
    inStock: true,
    href: "/produto/cabo-lightning-usb-c",
  },
  {
    id: "21",
    name: "Carregador Wireless 15W",
    price: 149.0,
    originalPrice: 199.0,
    image: "/images/carregador-wireless.png",
    rating: 4.5,
    reviews: 289,
    category: "Smartphones & Tablets",
    subcategory: "Acessórios",
    brand: "Samsung",
    description: "Carregador sem fio de 15W com tecnologia de carregamento rápido e design elegante.",
    specifications: {
      Potência: "15W",
      Compatibilidade: "Qi Wireless",
      Entrada: "USB-C",
      Indicador: "LED",
      Proteção: "Sobrecarga e superaquecimento",
    },
    inStock: true,
    colors: ["Preto", "Branco"],
    href: "/produto/carregador-wireless-15w",
  },
  {
    id: "22",
    name: "Fone Bluetooth Earbuds Pro",
    price: 299.0,
    originalPrice: 399.0,
    image: "/images/fone-bluetooth-earbuds.png",
    rating: 4.6,
    reviews: 567,
    category: "Smartphones & Tablets",
    subcategory: "Acessórios",
    brand: "Samsung",
    description: "Earbuds Bluetooth com cancelamento ativo de ruído, resistência à água IPX7 e até 8h de bateria.",
    specifications: {
      Conectividade: "Bluetooth 5.2",
      "Cancelamento de Ruído": "Ativo (ANC)",
      Bateria: "8h + 24h no estojo",
      Resistência: "IPX7",
      Drivers: "11mm",
    },
    inStock: true,
    colors: ["Preto", "Branco", "Grafite"],
    href: "/produto/earbuds-bluetooth-pro",
  },
  {
    id: "23",
    name: "Adaptador USB-C para USB-A",
    price: 49.0,
    image: "/images/adaptador-usb-c.png",
    rating: 4.3,
    reviews: 123,
    category: "Smartphones & Tablets",
    subcategory: "Acessórios",
    brand: "Apple",
    description: "Adaptador compacto USB-C para USB-A, perfeito para conectar dispositivos antigos aos novos.",
    specifications: {
      Conectores: "USB-C para USB-A",
      Velocidade: "USB 3.0",
      Material: "Alumínio",
      Dimensões: "2,5 x 1,2 x 0,8 cm",
      Peso: "8g",
    },
    inStock: true,
    href: "/produto/adaptador-usb-c-usb-a",
  },
  {
    id: "24",
    name: "Cabo USB-C para USB-C 2m",
    price: 79.0,
    originalPrice: 99.0,
    image: "/images/cabo-usb-c.png",
    rating: 4.5,
    reviews: 234,
    category: "Smartphones & Tablets",
    subcategory: "Acessórios",
    brand: "Samsung",
    description: "Cabo USB-C para USB-C de 2 metros, suporta carregamento rápido e transferência de dados.",
    specifications: {
      Comprimento: "2 metros",
      Conectores: "USB-C para USB-C",
      Velocidade: "USB 3.1",
      Potência: "100W",
      Material: "Cabo reforçado",
    },
    inStock: true,
    colors: ["Preto", "Branco"],
    href: "/produto/cabo-usb-c-2m",
  },
  {
    id: "25",
    name: "Suporte Ajustável para Celular",
    price: 59.0,
    image: "/images/suporte-celular.png",
    rating: 4.4,
    reviews: 189,
    category: "Smartphones & Tablets",
    subcategory: "Acessórios",
    brand: "Universal",
    description: "Suporte ajustável universal para smartphones e tablets, ideal para mesa e escritório.",
    specifications: {
      Compatibilidade: "4-12 polegadas",
      Material: "Alumínio + ABS",
      Ajuste: "Altura e ângulo",
      Base: "Antiderrapante",
      Peso: "200g",
    },
    inStock: true,
    colors: ["Preto", "Prata"],
    href: "/produto/suporte-celular-ajustavel",
  },
  {
    id: "26",
    name: "Power Bank 20000mAh USB-C",
    price: 199.0,
    originalPrice: 249.0,
    image: "/images/carregador-portatil.png",
    rating: 4.7,
    reviews: 345,
    category: "Smartphones & Tablets",
    subcategory: "Acessórios",
    brand: "Xiaomi",
    description: "Carregador portátil de 20000mAh com USB-C PD, carregamento rápido e display digital.",
    specifications: {
      Capacidade: "20000mAh",
      "Entrada USB-C": "18W",
      "Saída USB-C": "22,5W",
      "Saída USB-A": "22,5W",
      Display: "LED Digital",
    },
    inStock: true,
    colors: ["Preto", "Branco"],
    href: "/produto/power-bank-20000mah",
  },
  {
    id: "27",
    name: "Capa Transparente com Proteção",
    price: 39.0,
    image: "/images/capa-transparente.png",
    rating: 4.2,
    reviews: 456,
    category: "Smartphones & Tablets",
    subcategory: "Acessórios",
    brand: "Universal",
    description: "Capa transparente com proteção anti-impacto, bordas elevadas e material TPU flexível.",
    specifications: {
      Material: "TPU transparente",
      Proteção: "Anti-impacto",
      Bordas: "Elevadas",
      Compatibilidade: "Múltiplos modelos",
      Espessura: "1,2mm",
    },
    inStock: true,
    href: "/produto/capa-transparente-protecao",
  },
]

export const eletrodomesticosProducts: Product[] = [
  {
    id: "7",
    name: "Geladeira Frost Free 400L Inox",
    price: 2299.0,
    originalPrice: 2799.0,
    image: "/images/geladeira-inox.png",
    rating: 4.6,
    reviews: 234,
    category: "Eletrodomésticos",
    subcategory: "Geladeiras",
    brand: "FrostTech",
    description: "Geladeira frost free de 400 litros em aço inox com tecnologia de resfriamento inteligente.",
    specifications: {
      Capacidade: "400L",
      Tipo: "Frost Free",
      Material: "Aço Inox",
      Voltagem: "110V/220V",
      Dimensões: "185x70x65cm",
    },
    inStock: true,
    href: "/produto/geladeira-frost-free-400l",
  },
  {
    id: "8",
    name: "Micro-ondas LG 30L Digital",
    price: 459.0,
    originalPrice: 559.0,
    image: "/images/microondas-lg.png",
    rating: 4.4,
    reviews: 189,
    category: "Eletrodomésticos",
    subcategory: "Micro-ondas",
    brand: "LG",
    description: "Micro-ondas digital de 30 litros com 10 níveis de potência e timer digital.",
    specifications: {
      Capacidade: "30L",
      Potência: "900W",
      Níveis: "10",
      Timer: "Digital",
      Voltagem: "110V/220V",
    },
    inStock: true,
    href: "/produto/microondas-30l-digital",
  },
  {
    id: "9",
    name: "Fogão 5 Bocas Automático Branco",
    price: 899.0,
    originalPrice: 1199.0,
    image: "/images/fogao-5-bocas.png",
    rating: 4.5,
    reviews: 156,
    category: "Eletrodomésticos",
    subcategory: "Fogões",
    brand: "CookMaster",
    description: "Fogão de 5 bocas com acendimento automático e forno com grill.",
    specifications: {
      Bocas: "5",
      Acendimento: "Automático",
      Forno: "Com Grill",
      Cor: "Branco",
      Dimensões: "87x60x55cm",
    },
    inStock: true,
    href: "/produto/fogao-5-bocas-automatico",
  },
]

export const audioVideoProducts: Product[] = [
  {
    id: "10",
    name: 'Smart TV LG OLED 65" 4K',
    price: 4999.0,
    originalPrice: 5999.0,
    image: "/images/tv-oled-lg.png",
    rating: 4.8,
    reviews: 456,
    category: "Áudio & Vídeo",
    subcategory: "TVs",
    brand: "LG",
    description: "Smart TV OLED de 65 polegadas com resolução 4K, HDR e sistema operacional webOS.",
    specifications: {
      Tamanho: "65 polegadas",
      Resolução: "4K (3840x2160)",
      Tecnologia: "OLED",
      HDR: "Sim",
      Sistema: "webOS",
      Conectividade: "Wi-Fi, Bluetooth",
    },
    inStock: true,
    href: "/produto/smart-tv-65-4k-oled",
  },
  {
    id: "11",
    name: "Soundbar 5.1 Dolby Atmos",
    price: 1299.0,
    image: "/images/soundbar-dolby-atmos.png",
    rating: 4.7,
    reviews: 234,
    category: "Áudio & Vídeo",
    subcategory: "Soundbars",
    brand: "AudioMax",
    description: "Soundbar 5.1 com tecnologia Dolby Atmos e subwoofer wireless.",
    specifications: {
      Canais: "5.1",
      Tecnologia: "Dolby Atmos",
      Subwoofer: "Wireless",
      Potência: "400W",
      Conectividade: "HDMI, Bluetooth",
    },
    inStock: true,
    href: "/produto/soundbar-51-dolby-atmos",
  },
]

export const gamingProducts: Product[] = [
  {
    id: "12",
    name: "PlayStation 5 Slim",
    price: 4199.0,
    image: "/images/playstation-5-bundle.png",
    rating: 4.9,
    reviews: 1234,
    category: "Gaming",
    subcategory: "Consoles",
    brand: "Sony",
    description: "Console PlayStation 5 Slim com SSD de 1TB e controle DualSense.",
    specifications: {
      Armazenamento: "1TB SSD",
      Resolução: "4K",
      "Ray Tracing": "Sim",
      Controle: "DualSense",
      Conectividade: "Wi-Fi 6, Bluetooth",
    },
    inStock: true,
    href: "/produto/playstation-5-slim",
  },
  {
    id: "13",
    name: "Xbox Series X",
    price: 4499.0,
    originalPrice: 4999.0,
    image: "/images/xbox-series-x.png",
    rating: 4.8,
    reviews: 856,
    category: "Gaming",
    subcategory: "Consoles",
    brand: "Microsoft",
    description: "Console Xbox Series X com 1TB de armazenamento e retrocompatibilidade.",
    specifications: {
      Armazenamento: "1TB SSD",
      Resolução: "4K",
      FPS: "120fps",
      Retrocompatibilidade: "Sim",
      "Game Pass": "Incluído",
    },
    inStock: true,
    href: "/produto/xbox-series-x",
  },
]

export const casaInteligenteProducts: Product[] = [
  {
    id: "14",
    name: "Alexa Echo Dot 5ª Geração",
    price: 299.0,
    originalPrice: 399.0,
    image: "/images/echo-dot-alexa.png",
    rating: 4.6,
    reviews: 567,
    category: "Casa Inteligente",
    subcategory: "Assistentes",
    brand: "Amazon",
    description: "Assistente virtual Alexa Echo Dot com som melhorado e hub integrado.",
    specifications: {
      Assistente: "Alexa",
      Conectividade: "Wi-Fi, Bluetooth",
      Hub: "Zigbee integrado",
      Som: "Melhorado",
      Controle: "Por voz",
    },
    inStock: true,
    href: "/produto/alexa-echo-dot-5-geracao",
  },
]

export const allProducts = [
  ...hardwareProducts,
  ...smartphonesProducts,
  ...eletrodomesticosProducts,
  ...audioVideoProducts,
  ...gamingProducts,
  ...casaInteligenteProducts,
]

export const getProductById = (id: string): Product | undefined => {
  return allProducts.find((product) => product.id === id)
}

export const getProductsByCategory = (category: string): Product[] => {
  return allProducts.filter((product) => product.category === category)
}

export const getProductsBySubcategory = (subcategory: string): Product[] => {
  return allProducts.filter((product) => product.subcategory === subcategory)
}
